# Generated by Django 5.1.2 on 2024-10-28 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
